import type { MetadataRoute } from "next";
import { site } from "@/content/site";
import { brandColors } from "@/lib/brand";

/** /manifest.webmanifest — name, colours and icons used when the site is saved to a home screen. */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: site.title,
    short_name: site.name,
    description: site.description,
    start_url: "/",
    display: "browser",
    background_color: brandColors.canvas,
    theme_color: brandColors.canvas,
    icons: [
      { src: "/icon.svg", sizes: "any", type: "image/svg+xml" },
      // Generated by src/app/apple-icon.tsx.
      { src: "/apple-icon", sizes: "180x180", type: "image/png" },
    ],
  };
}
